"""Add quantity to Item.

Revision ID: 631ba21d19b2
Revises: 8a1926b919d0
Create Date: 2023-07-29 02:33:25.452169

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "631ba21d19b2"
down_revision = "8a1926b919d0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
