api_title = "Example FastAPI App"
api_description = "An example API built with FastAPI."
api_version = "0.1.0"

api_host = "0.0.0.0"
api_port = "8000"
api_reload = true
api_debug = true

api_origins = ["*"]
