"""${commit_msg}

Revision ID: 4f1e72884ad3
Revises: 631ba21d19b2
Create Date: 2023-07-29 02:41:36.362976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1e72884ad3'
down_revision = '631ba21d19b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
